language: cpp

compiler:
    - clang
    - gcc

before_install:
    - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi;
    - sudo apt-get update -qq;
    - sudo apt-get install -qq libcairo2-dev libx11-dev libxtst-dev libpango1.0-dev cmake;
    - mkdir ../xgac-build
      

install:
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; export CC="gcc-4.9"; export CXX="g++-4.9"; fi;


script:
    - cd ../xgac-build
    - cmake ../XGac
    - make

